ONBOARDING_TOKEN_EXP_MINS = 20
ACCESS_TOKEN_EXP_MINS = 15
REFRESH_TOKEN_EXP_DAYS = 7  # days
MAX_FAILED_OTP_ATTEMPTS = 3
ACCOUNT_LOCKOUT_DURATION_MINUTES = 15
# Argon2 constants
ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST = 65536
ARGON2_PARALLELISM = 4
ARGON2_HASH_LEN = 32
ARGON2_SALT_LEN = 16

# Blnk ledgers
CUSTOMER_WALLET_LEDGER = "Customer Wallets Ledger"

# Blockrader wallets
MASTER_BASE_WALLET = "master_base_wallet"


# DOAMINS

STAGING_DOMAIN = "staging.looprail.xyz"
PRODUCTION_DOMAIN = "looprail.xyz"

BANK_TRASNFER_WITHDRAWAL_FEE = "0.1"
