"""feat: added rate to column

Revision ID: 03c3bb90dbb4
Revises: 3b432ba40316
Create Date: 2026-03-22 02:20:02.707716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03c3bb90dbb4'
down_revision: Union[str, None] = '3b432ba40316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transfer_details', sa.Column('rate', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transfer_details', 'rate')
    # ### end Alembic commands ###
