"""fix

Revision ID: 075ddcfbdc48
Revises: abbc99965a71
Create Date: 2026-03-08 23:32:55.966540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '075ddcfbdc48'
down_revision: Union[str, None] = 'abbc99965a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('region_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('transactions', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'meta_data')
    op.drop_column('sessions', 'longitude')
    op.drop_column('sessions', 'latitude')
    op.drop_column('sessions', 'city')
    op.drop_column('sessions', 'region_name')
    op.drop_column('sessions', 'country_code')
    op.drop_column('sessions', 'country')
    op.drop_column('sessions', 'user_agent')
    # ### end Alembic commands ###
