"""feat: add passcode_hash to sessions and user_biometrics table

Revision ID: 0fe904450fad
Revises: 8efdc0ba1a66
Create Date: 2026-01-18 20:37:53.978170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0fe904450fad"
down_revision: Union[str, None] = "8efdc0ba1a66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_biometrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_biometrics_device_id"),
        "user_biometrics",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_biometrics_user_id"), "user_biometrics", ["user_id"], unique=False
    )
    op.add_column(
        "sessions",
        sa.Column("passcode_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_sessions_last_seen_at"), "sessions", ["last_seen_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_last_seen_at"), table_name="sessions")
    op.drop_column("sessions", "passcode_hash")
    op.drop_index(op.f("ix_user_biometrics_user_id"), table_name="user_biometrics")
    op.drop_index(op.f("ix_user_biometrics_device_id"), table_name="user_biometrics")
    op.drop_table("user_biometrics")
    # ### end Alembic commands ###
