"""fix: added email notificaitons field to user modes

Revision ID: 1872f006b306
Revises: c1a2b477d130
Create Date: 2026-04-18 17:06:14.480325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1872f006b306'
down_revision: Union[str, None] = 'c1a2b477d130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
