"""feat: add country and payment type to transactions and update user profile country

Revision ID: 1916bd7749f8
Revises: c49a53f38044
Create Date: 2026-01-19 03:13:23.874365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1916bd7749f8"
down_revision: Union[str, None] = "c49a53f38044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "payment_type",
            sa.Enum(
                "CRYPTO_SEND",
                "CRYPTO_RECEIVE",
                "CRYPTO_SWAP",
                "BANK_WITHDRAWAL",
                "BANK_DEPOSIT",
                "CARD_DEPOSIT",
                "INTERNAL_TRANSFER",
                "FEE",
                "REFUND",
                "DEBIT",
                "CREDIT",
                name="transactiontype",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_transactions_country"), "transactions", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_payment_type"),
        "transactions",
        ["payment_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_payment_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_country"), table_name="transactions")
    op.drop_column("transactions", "country")
    op.drop_column("transactions", "payment_type")
    # ### end Alembic commands ###
