"""ref: added paycrest txn type

Revision ID: 1ed93ce85b1d
Revises: baceafafde75
Create Date: 2026-03-23 13:27:00.770999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ed93ce85b1d'
down_revision: Union[str, None] = 'baceafafde75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
