"""feat: asset id non unique

Revision ID: 29481d883948
Revises: f535e8dc3c62
Create Date: 2026-01-21 03:10:22.213423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29481d883948'
down_revision: Union[str, None] = 'f535e8dc3c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    # ### end Alembic commands ###
