"""feat: added ledger txn id

Revision ID: 3348650d927f
Revises: 29481d883948
Create Date: 2026-01-24 23:31:36.040785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3348650d927f"
down_revision: Union[str, None] = "29481d883948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "ledger_transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_unique_constraint(None, "transactions", ["ledger_transaction_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="unique")
    op.drop_column("transactions", "ledger_transaction_id")
    # ### end Alembic commands ###
