"""fix

Revision ID: 3b432ba40316
Revises: 192fadf78cb1
Create Date: 2026-03-13 15:43:14.161826

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b432ba40316"
down_revision: Union[str, None] = "192fadf78cb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE transactionstatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
