"""initial migration

Revision ID: 568e2831b55b
Revises:
Create Date: 2026-01-05 05:46:58.830758

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "568e2831b55b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
