"""fix: made asset id unique

Revision ID: 611b0b7b1ba3
Revises: 1916bd7749f8
Create Date: 2026-01-20 02:53:15.427564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "611b0b7b1ba3"
down_revision: Union[str, None] = "1916bd7749f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=False)
    # ### end Alembic commands ###
