"""feat: updated models

Revision ID: 7332c348b6ee
Revises: c40117c9f219
Create Date: 2026-03-13 11:25:32.429270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7332c348b6ee'
down_revision: Union[str, None] = 'c40117c9f219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deposit_stage', postgresql.ENUM('PENDING', 'RECEIVED', 'SWEPT', name='depositstage', create_type=False), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_deposit_details_deposit_stage'), 'deposit_details', ['deposit_stage'], unique=False)
    op.create_index(op.f('ix_deposit_details_provider_reference'), 'deposit_details', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_deposit_details_source_reference'), 'deposit_details', ['source_reference'], unique=False)
    op.create_table('internal_transfer_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transfer_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_internal_transfer_details_recipient_user_id'), 'internal_transfer_details', ['recipient_user_id'], unique=False)
    op.drop_index(op.f('ix_transactions_deposit_stage'), table_name='transactions')
    op.drop_column('transactions', 'deposit_stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deposit_stage', postgresql.ENUM('PENDING', 'RECEIVED', 'SWEPT', name='depositstage'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transactions_deposit_stage'), 'transactions', ['deposit_stage'], unique=False)
    op.drop_index(op.f('ix_internal_transfer_details_recipient_user_id'), table_name='internal_transfer_details')
    op.drop_table('internal_transfer_details')
    op.drop_index(op.f('ix_deposit_details_source_reference'), table_name='deposit_details')
    op.drop_index(op.f('ix_deposit_details_provider_reference'), table_name='deposit_details')
    op.drop_index(op.f('ix_deposit_details_deposit_stage'), table_name='deposit_details')
    op.drop_table('deposit_details')
    # ### end Alembic commands ###
