"""fix: change country short name

Revision ID: 7567d3d3eedc
Revises: d5b6d0e8183f
Create Date: 2026-04-17 12:26:16.779344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7567d3d3eedc'
down_revision: Union[str, None] = 'd5b6d0e8183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
