"""feat: added user crednetials ans user pin fields

Revision ID: 7f77ae6ee9cd
Revises: b46be8ef3674
Create Date: 2026-01-17 03:19:28.784912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7f77ae6ee9cd"
down_revision: Union[str, None] = "b46be8ef3674"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_credentials_user_id"),
        "user_credentials",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "user_pins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pin_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_pins_user_id"), "user_pins", ["user_id"], unique=True)
    op.add_column(
        "user_profiles",
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "ledger_identity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_ledger_identiy_id_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_unique_constraint(None, "users", ["ledger_identity_id"])
    op.drop_column("users", "salt")
    op.drop_column("users", "ledger_identiy_id")
    op.drop_column("users", "transaction_pin")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("transaction_pin", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "ledger_identiy_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("salt", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_ledger_identiy_id_key"),
        "users",
        ["ledger_identiy_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "ledger_identity_id")
    op.drop_column("user_profiles", "postal_code")
    op.drop_index(op.f("ix_user_pins_user_id"), table_name="user_pins")
    op.drop_table("user_pins")
    op.drop_index(op.f("ix_user_credentials_user_id"), table_name="user_credentials")
    op.drop_table("user_credentials")
    # ### end Alembic commands ###
