"""Refactor transaction DTO and model defaults and fix sqlalchemy metadata conflict

Revision ID: 8efdc0ba1a66
Revises: 21b710294929
Create Date: 2026-01-18 00:24:05.447643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8efdc0ba1a66"
down_revision: Union[str, None] = "ced53f313f36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_transfer_details",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bank_code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "bank_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "account_number",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "account_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("account_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_date", sa.DateTime(), nullable=True),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "provider_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_bank_transfer_details_account_number"),
        "bank_transfer_details",
        ["account_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transfer_details_bank_code"),
        "bank_transfer_details",
        ["bank_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transfer_details_provider_reference"),
        "bank_transfer_details",
        ["provider_reference"],
        unique=False,
    )
    op.create_table(
        "wallet_transfer_details",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "wallet_address",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column(
            "network", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("address_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "contract_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_wallet_transfer_details_wallet_address"),
        "wallet_transfer_details",
        ["wallet_address"],
        unique=False,
    )

    op.add_column(
        "transactions",
        sa.Column(
            "external_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "narration", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "destination_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "extra_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    sa.Enum("COMPLETED", "PENDING", "FAILED", name="transactionstatus").create(
        op.get_bind()
    )
    op.alter_column(
        "transactions",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("COMPLETED", "PENDING", "FAILED", name="transactionstatus"),
        existing_nullable=False,
        postgresql_using="status::transactionstatus",
    )
    op.alter_column(
        "transactions", "transaction_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "transactions", "network", existing_type=sa.VARCHAR(), nullable=True
    )

    op.create_index(
        op.f("ix_transactions_external_reference"),
        "transactions",
        ["external_reference"],
        unique=False,
    )

    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )

    op.create_index(
        op.f("ix_transactions_transaction_type"),
        "transactions",
        ["transaction_type"],
        unique=False,
    )

    op.drop_column("transactions", "note")
    op.drop_column("transactions", "provider_id")
    op.drop_column("transactions", "reason")


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_user_pins_user_id"), table_name="user_pins")
    op.drop_index(op.f("ix_user_credentials_user_id"), table_name="user_credentials")
    op.add_column(
        "transactions",
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("provider_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column("note", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    op.drop_index(op.f("ix_transactions_transaction_type"), table_name="transactions")

    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_reference"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_external_reference"), table_name="transactions")

    op.alter_column(
        "transactions", "network", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "transactions", "transaction_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "transactions",
        "status",
        existing_type=sa.Enum(
            "COMPLETED", "PENDING", "FAILED", name="transactionstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_enum("transactionstatus")
    op.drop_column("transactions", "extra_data")
    op.drop_column("transactions", "destination_data")
    op.drop_column("transactions", "narration")
    op.drop_column("transactions", "external_reference")
    
    op.drop_index(
        op.f("ix_wallet_transfer_details_wallet_address"),
        table_name="wallet_transfer_details",
    )
    op.drop_table("wallet_transfer_details")
    op.drop_index(
        op.f("ix_bank_transfer_details_provider_reference"),
        table_name="bank_transfer_details",
    )
    op.drop_index(
        op.f("ix_bank_transfer_details_bank_code"), table_name="bank_transfer_details"
    )
    op.drop_index(
        op.f("ix_bank_transfer_details_account_number"),
        table_name="bank_transfer_details",
    )
    op.drop_table("bank_transfer_details")
    # ### end Alembic commands ###
