"""fix: precision

Revision ID: 9e6fec8d1b36
Revises: 2f4755197542
Create Date: 2026-03-09 11:59:38.714216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e6fec8d1b36'
down_revision: Union[str, None] = '2f4755197542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'precision',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'precision',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
