"""feat: add device info fields to sessions

Revision ID: 9e87e3bd35b3
Revises: 7567d3d3eedc
Create Date: 2026-04-18 11:57:35.967133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e87e3bd35b3'
down_revision: Union[str, None] = '7567d3d3eedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('device_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('device_manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('device_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('sdk_int', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'sdk_int')
    op.drop_column('sessions', 'os_version')
    op.drop_column('sessions', 'device_product')
    op.drop_column('sessions', 'device_name')
    op.drop_column('sessions', 'device_manufacturer')
    op.drop_column('sessions', 'device_brand')
    op.drop_column('sessions', 'device_model')
    # ### end Alembic commands ###
