"""empty message

Revision ID: 9f2171d2310b
Revises: 026d04fbf17f
Create Date: 2026-01-05 02:26:25.339503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f2171d2310b'
down_revision: Union[str, None] = '026d04fbf17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_provider_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_provider_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('user_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('kyc_status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='kycstatus'), autoincrement=False, nullable=False),
    sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usdc_asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('derivation_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallets_provider_id'), 'wallets', ['provider_id'], unique=True)
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('DEBIT', 'CREDIT', name='transactiontype'), autoincrement=False, nullable=False),
    sa.Column('method', postgresql.ENUM('CARD', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_TRANSFER', 'MOBILE_MONEY', 'WALLET_TRANSFER', name='transactionmethod'), autoincrement=False, nullable=False),
    sa.Column('currency', postgresql.ENUM('NGN', 'USD', name='supportedcurrencies'), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiver', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gas_price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gas_fee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gas_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('transactions_wallet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_hash'), 'transactions', ['transaction_hash'], unique=True)
    op.create_index(op.f('ix_transactions_provider_id'), 'transactions', ['provider_id'], unique=True)
    # ### end Alembic commands ###
