"""feat: removed blockrader_asset_id in favour of asset_id

Revision ID: a04f0f42db98
Revises: 58c1225cc496
Create Date: 2026-01-16 21:36:56.856806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a04f0f42db98"
down_revision: Union[str, None] = "58c1225cc496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("asset_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_assets_blockrader_asset_id"), table_name="assets")
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=False)
    op.drop_column("assets", "blockrader_asset_id")
    op.create_unique_constraint(None, "user_profiles", ["phone_number"])
    op.drop_column("user_profiles", "postal_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column("postal_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_profiles", type_="unique")
    op.add_column(
        "assets",
        sa.Column(
            "blockrader_asset_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.create_index(
        op.f("ix_assets_blockrader_asset_id"),
        "assets",
        ["blockrader_asset_id"],
        unique=False,
    )
    op.drop_column("assets", "asset_id")
    # ### end Alembic commands ###
