"""feat: deposite stage to deposit txn

Revision ID: a4ecae07a6b4
Revises: 9e6fec8d1b36
Create Date: 2026-03-10 03:41:34.898200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4ecae07a6b4'
down_revision: Union[str, None] = '9e6fec8d1b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    deposit_stage_enum = sa.Enum('PENDING', 'RECEIVED', 'SWEPT', name='depositstage')
    deposit_stage_enum.create(op.get_bind())

    op.add_column('transactions', sa.Column('deposit_stage', deposit_stage_enum, nullable=True))
    op.create_index(op.f('ix_transactions_deposit_stage'), 'transactions', ['deposit_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_deposit_stage'), table_name='transactions')
    op.drop_column('transactions', 'deposit_stage')

    # Drop the enum type
    deposit_stage_enum = sa.Enum('PENDING', 'RECEIVED', 'SWEPT', name='depositstage')
    deposit_stage_enum.drop(op.get_bind())
    # ### end Alembic commands ###
