"""added fcm

Revision ID: a51a23755245
Revises: efe4521eb9cc
Create Date: 2026-02-26 03:02:05.924063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a51a23755245'
down_revision: Union[str, None] = 'efe4521eb9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    network_enum = postgresql.ENUM('MAINNET', 'TESTNET', name='network', create_type=False)
    
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        result = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'network'")).scalar()
        if not result:
            network_enum.create(bind)

    op.alter_column('assets', 'network',
               existing_type=sa.VARCHAR(),
               type_=network_enum,
               existing_nullable=False,
               postgresql_using='UPPER(network)::network')
    op.add_column('sessions', sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('transactions', 'network',
               existing_type=sa.VARCHAR(),
               type_=network_enum,
               existing_nullable=True,
               postgresql_using='UPPER(network)::network')
    if bind.dialect.name == 'postgresql':
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_transactions_reference ON transactions (reference)')
    else:
        op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.alter_column('wallet_transfer_details', 'network',
               existing_type=sa.VARCHAR(length=50),
               type_=network_enum,
               existing_nullable=False,
               postgresql_using='UPPER(network)::network')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    network_enum = postgresql.ENUM('MAINNET', 'TESTNET', name='network', create_type=False)

    op.alter_column('wallet_transfer_details', 'network',
               existing_type=network_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP INDEX IF EXISTS ix_transactions_reference')
    else:
        op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.alter_column('transactions', 'network',
               existing_type=network_enum,
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('sessions', 'fcm_token')
    op.alter_column('assets', 'network',
               existing_type=network_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False)
               
    network_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
