"""Add paycrest fields

Revision ID: baceafafde75
Revises: 03c3bb90dbb4
Create Date: 2026-03-23 12:37:35.527082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'baceafafde75'
down_revision: Union[str, None] = '03c3bb90dbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transfer_details', sa.Column('paycrest_txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bank_transfer_details', sa.Column('paycrest_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_bank_transfer_details_paycrest_txn_id'), 'bank_transfer_details', ['paycrest_txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transfer_details_paycrest_txn_id'), table_name='bank_transfer_details')
    op.drop_column('bank_transfer_details', 'paycrest_status')
    op.drop_column('bank_transfer_details', 'paycrest_txn_id')
    # ### end Alembic commands ###
