"""fix: moved session_id

Revision ID: c40117c9f219
Revises: a4ecae07a6b4
Create Date: 2026-03-13 03:51:20.330652

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c40117c9f219"
down_revision: Union[str, None] = "a4ecae07a6b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "precision", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("bank_transfer_details", "session_id")
    op.add_column("transactions", sa.Column("session_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "session_id")
    op.add_column(
        "bank_transfer_details",
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("assets", "precision", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
