"""fix: type hints

Revision ID: ced53f313f36
Revises: 7f77ae6ee9cd
Create Date: 2026-01-17 04:01:31.351306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ced53f313f36'
down_revision: Union[str, None] = '7f77ae6ee9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('allow_notifications', sa.Boolean(), nullable=False))
    op.alter_column('user_profiles', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user_profiles', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sessions', 'allow_notifications')
    # ### end Alembic commands ###
