"""removed balances from wallets

Revision ID: e9d1998c6aa1
Revises: c08996290f94
Create Date: 2026-01-05 15:52:35.731452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d1998c6aa1'
down_revision: Union[str, None] = 'c08996290f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
