[[ledgers]]
name = "Customer Wallets Ledger"
ledger_id = "ldg_b77da1c7-45b1-419f-9713-ee1da97f79da" 
meta_data = { description = "Ledger for managing customer wallets", application = "Wallet Management System" }

