[[ledgers]]
name = "Customer Wallets Ledger"
ledger_id = "ldg_b1114b38-545c-4f48-b0b5-786fe08347f8" # TODO load from .env
meta_data = { description = "Ledger for managing customer wallets", application = "Wallet Management System" }

